import { ensureFreshSession } from '../auth';
export type SupportedCurrency='USD'|'ZiG'|'ZAR';
export type DeliveryMethod='pickup'|'standard'|'express';
export type DeliveryStatus='pending'|'preparing'|'ready_for_pickup'|'out_for_delivery'|'delivered'|'failed'|'cancelled';
export type DeliveryHistoryEntry={fromStatus:DeliveryStatus|null;toStatus:DeliveryStatus;trackingReference?:string;changedAt:string};
export type DeliverySummary={status:DeliveryStatus;trackingReference?:string;scheduledFor?:string;deliveredAt?:string;history:DeliveryHistoryEntry[]};
export type DeliveryOption={method:DeliveryMethod;label:string;description:string;fee:number};
export const DELIVERY_OPTIONS:DeliveryOption[]=[{method:'pickup',label:'Store pickup',description:'Collect your order from the store.',fee:0},{method:'standard',label:'Standard delivery',description:'Reliable scheduled household delivery.',fee:3},{method:'express',label:'Express delivery',description:'Priority delivery when available.',fee:6}];
export type Product={id:string;name:string;category:string;productFamily?:string;brand?:string;variantLabel?:string;sizeLabel?:string;price:number;currency:string;available:boolean}; export type BasketItem={productId:string;quantity:number;unitPrice:number;currency:string}; export type Basket={id:string;items:BasketItem[]};
export type Order={id:string;status:string;subtotal:number;deliveryMethod:DeliveryMethod;deliveryFee:number;total:number;currency:string;items:BasketItem[];delivery?:DeliverySummary;createdAt?:string};
export type Notification={id:string;type:string;title:string;body:string;status:'unread'|'read'|'archived';aggregateType?:string;aggregateId?:string;actionType?:string;actionTarget?:string;createdAt:string};
export type BuckPayAccount={balance:number;currency:string;status:'active'|'suspended'}; export type BuckPayTransaction={id:string;type:'earned_reward'|'customer_funding'|'commerce_redemption'|'reversal';amount:number;currency:string;reference:string;createdAt:string};
export const SUPPORTED_CURRENCIES=[{code:'USD' as SupportedCurrency,label:'USD',symbol:'$'},{code:'ZiG' as SupportedCurrency,label:'ZiG',symbol:'ZiG'},{code:'ZAR' as SupportedCurrency,label:'ZAR',symbol:'R'}];
export const DISPLAY_RATES_FROM_ZIG:Record<SupportedCurrency,number>={ZiG:1,USD:.0275,ZAR:.49}; export function formatMoney(amount:number,currency:SupportedCurrency){const m=SUPPORTED_CURRENCIES.find(x=>x.code===currency);return`${m?.symbol??currency}${amount.toFixed(2)}`;} export function convertDisplayAmount(amount:number,from:string,to:SupportedCurrency){if(from===to)return amount;const a=DISPLAY_RATES_FROM_ZIG[from as SupportedCurrency],b=DISPLAY_RATES_FROM_ZIG[to];return!a||!b?amount:(amount/a)*b;}
export interface CommerceClient{listProducts():Promise<Product[]>;getProduct(productId:string):Promise<Product>;getBasket():Promise<Basket>;addBasketItem(productId:string,quantity:number):Promise<Basket>;removeBasketItem(productId:string):Promise<Basket>;checkout(deliveryMethod:DeliveryMethod):Promise<Order>;listOrders():Promise<Order[]>;getOrder(orderId:string):Promise<Order>;listNotifications():Promise<Notification[]>;markNotificationRead(notificationId:string):Promise<Notification>;getBuckPayAccount():Promise<BuckPayAccount>;getBuckPayTransactions():Promise<BuckPayTransaction[]>;}
const API_BASE_URL=import.meta.env.VITE_COMMERCE_API_URL??'/api'; const categoryFor=(id:string):string=>({bread:'Bakery',milk:'Dairy',eggs:'Dairy', 'discontinued-item':'Household',rice:'Pantry',soap:'Household',toothpaste:'Personal Care'}[id]??'Essentials'); const sleep=(ms:number)=>new Promise(r=>window.setTimeout(r,ms));
async function request<T>(path:string,init?:RequestInit):Promise<T>{const method=(init?.method??'GET').toUpperCase(),attempts=method==='GET'?2:1;let lastError:Error|null=null;for(let attempt=1;attempt<=attempts;attempt++){try{const session=await ensureFreshSession();const headers=new Headers(init?.headers);headers.set('Accept','application/json');if(init?.body)headers.set('Content-Type','application/json');if(session?.access_token)headers.set('Authorization',`Bearer ${session.access_token}`);const c=new AbortController(),t=window.setTimeout(()=>c.abort(),12000);try{const response=await fetch(`${API_BASE_URL}${path}`,{...init,headers,signal:c.signal});const text=await response.text();let body:unknown;try{body=text?JSON.parse(text):null;}catch{throw new Error(`Commerce API returned an invalid response (${response.status}).`);}if(!response.ok){const eb=body as{error?:{message?:string}}|null;const msg=eb?.error?.message??`Commerce request failed (${response.status}).`;if(response.status===401)throw new Error('Please sign in again to continue.');if(method==='GET'&&(response.status>=500||response.status===429)&&attempt<attempts){await sleep(150);continue;}throw new Error(msg);}if(body==null)throw new Error('Commerce API returned an empty response.');return body as T;}finally{window.clearTimeout(t);}}catch(err){lastError=err instanceof Error?err:new Error('Commerce request failed.');const retry=lastError.name==='AbortError'||lastError.message==='Failed to fetch'||lastError.message.includes('fetch failed');if(method==='GET'&&attempt<attempts&&retry){await sleep(150);continue;}throw lastError;}}throw lastError??new Error('Commerce request failed.');}
type ProductDto={id:string;name:string;category?:string;productFamily?:string;brand?:string;variantLabel?:string;sizeLabel?:string;price:{amountMinor:number;currency:string};available:boolean}; type BasketDto={id:string;lines:Array<{productId:string;quantity:number;unitPrice:{amountMinor:number;currency:string}}>}; type DeliveryHistoryDto={fromStatus:DeliveryStatus|null;toStatus:DeliveryStatus;trackingReference?:string;changedAt:string}; type DeliveryDto={status:DeliveryStatus;trackingReference?:string;scheduledFor?:string;deliveredAt?:string;history:DeliveryHistoryDto[]}; type OrderDto={id:string;status:string;subtotal:{amountMinor:number;currency:string};deliveryMethod:DeliveryMethod;deliveryFee:{amountMinor:number;currency:string};total:{amountMinor:number;currency:string};lines:Array<{productId:string;quantity:number;unitPrice:{amountMinor:number;currency:string}}>;delivery?:DeliveryDto;createdAt?:string}; type NotificationDto={id:string;type:string;title:string;body:string;status:'unread'|'read'|'archived';aggregateType?:string;aggregateId?:string;actionType?:string;actionTarget?:string;createdAt:string};
const fromProduct=(p:ProductDto):Product=>({id:p.id,name:p.name.replace(' [DEV FIXTURE]',''),category:p.category??categoryFor(p.id),productFamily:p.productFamily,brand:p.brand,variantLabel:p.variantLabel,sizeLabel:p.sizeLabel,price:p.price.amountMinor/100,currency:p.price.currency,available:p.available}); const fromBasket=(b:BasketDto):Basket=>({id:b.id,items:b.lines.map(l=>({productId:l.productId,quantity:l.quantity,unitPrice:l.unitPrice.amountMinor/100,currency:l.unitPrice.currency}))}); const fromOrder=(o:OrderDto):Order=>({id:o.id,status:o.status,subtotal:o.subtotal.amountMinor/100,deliveryMethod:o.deliveryMethod,deliveryFee:o.deliveryFee.amountMinor/100,total:o.total.amountMinor/100,currency:o.total.currency,items:o.lines.map(l=>({productId:l.productId,quantity:l.quantity,unitPrice:l.unitPrice.amountMinor/100,currency:l.unitPrice.currency})),delivery:o.delivery,createdAt:o.createdAt}); const fromNotification=(n:NotificationDto):Notification=>n;
export const commerceClient:CommerceClient={async listProducts(){const r=await request<{products:ProductDto[]}>('/products');return r.products.map(fromProduct);},async getProduct(id){return fromProduct(await request<ProductDto>(`/products/${encodeURIComponent(id)}`));},async getBasket(){return fromBasket(await request<BasketDto>('/basket'));},async addBasketItem(productId,quantity){return fromBasket(await request<BasketDto>('/basket/items',{method:'POST',body:JSON.stringify({productId,quantity})}));},async removeBasketItem(id){return fromBasket(await request<BasketDto>(`/basket/items/${encodeURIComponent(id)}`,{method:'DELETE'}));},async checkout(deliveryMethod){return fromOrder(await request<OrderDto>('/checkout',{method:'POST',body:JSON.stringify({deliveryMethod})}));},async listOrders(){const r=await request<{orders:OrderDto[]}>('/orders');return r.orders.map(fromOrder);},async getOrder(id){return fromOrder(await request<OrderDto>(`/orders/${encodeURIComponent(id)}`));},async listNotifications(){const r=await request<{notifications:NotificationDto[]}>('/notifications');return r.notifications.map(fromNotification);},async markNotificationRead(id){return fromNotification(await request<NotificationDto>(`/notifications/${encodeURIComponent(id)}/read`,{method:'POST'}));},async getBuckPayAccount(){const d=await request<any>('/buckpay');return{balance:d.balance.amountMinor/100,currency:d.balance.currency,status:d.status};},async getBuckPayTransactions(){const r=await request<any>('/buckpay/transactions');return r.transactions.map((x:any)=>({id:x.id,type:x.type,amount:x.amount.amountMinor/100,currency:x.amount.currency,reference:x.reference,createdAt:x.createdAt}));}};
