import { SupabaseBuckPayRepository } from '../../../services/commerce-api/src/adapters/supabase/SupabaseBuckPayRepository.js';
import { BuckPayApplicationService } from '../../../services/commerce-api/src/application/BuckPayApplicationService.js';
import { CommerceApplicationService } from '../../../services/commerce-api/src/application/CommerceApplicationService.js';
import { SupabaseProductRepository,SupabaseBasketRepository,SupabaseOrderRepository,SupabaseCheckoutTransaction } from '../../../services/commerce-api/src/adapters/supabase/SupabaseCommerceRepositories.js';
import type { AuthenticatedPrincipal } from '../../../services/commerce-api/src/domain.js'; import { devPrincipal,principal as authPrincipal } from './_auth.js';
const commerce=new CommerceApplicationService(new SupabaseProductRepository(),new SupabaseBasketRepository(),new SupabaseOrderRepository(),new SupabaseCheckoutTransaction());const buckPay=new BuckPayApplicationService(new SupabaseBuckPayRepository());
function json(res:any,status:number,body:unknown){res.status(status).setHeader('Content-Type','application/json').send(JSON.stringify(body));}function error(res:any,status:number,code:string,message:string){json(res,status,{error:{code,message}});}function productDto(p:any){return{id:p.id,name:p.name,price:p.price,available:p.available};}function basketDto(b:any){return{id:b.id,lines:b.lines};}function orderDto(o:any){return{id:o.id,status:o.status,total:o.total,subtotal:o.subtotal,deliveryMethod:o.deliveryMethod,deliveryFee:o.deliveryFee,createdAt:o.createdAt,lines:o.lines};}
function requestPath(req:any){const u=typeof req.url==='string'?req.url:'';const p=u.split('?')[0];if(p.startsWith('/api/'))return decodeURIComponent(p.slice('/api'.length));if(p==='/api')return'/';const raw=typeof req.query?.path==='string'?`/${req.query.path}`:Array.isArray(req.query?.path)?`/${req.query.path.join('/')}`:'/';return decodeURIComponent(raw);}async function resolvePrincipal(req:any):Promise<AuthenticatedPrincipal|null>{const d=devPrincipal(req);if(d)return d;return authPrincipal(req);}
export default async function handler(req:any,res:any){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, x-dev-customer-id');res.setHeader('Vary','Origin, Authorization');if(req.method==='OPTIONS')return res.status(204).end();const path=requestPath(req);try{if(path==='/products'&&req.method==='GET')return json(res,200,{products:(await commerce.listProducts()).map(productDto)});if(path.startsWith('/products/')&&req.method==='GET')return json(res,200,productDto(await commerce.getProduct(path.slice('/products/'.length))));const user=await resolvePrincipal(req);if(!user)return error(res,401,'UNAUTHENTICATED','A valid Supabase Auth session is required.');if(path==='/basket'&&req.method==='GET')return json(res,200,basketDto(await commerce.getOrCreateBasket(user)));if(path==='/basket/items'&&req.method==='POST'){const body=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!body||typeof body.productId!=='string'||!Number.isInteger(body.quantity)||body.quantity<=0)return error(res,400,'VALIDATION_ERROR','productId must be a non-empty string and quantity must be a positive integer.');return json(res,201,basketDto(await commerce.addItem(user,body.productId,body.quantity)));}if(path.startsWith('/basket/items/')&&req.method==='DELETE')return json(res,200,basketDto(await commerce.removeItem(user,path.slice('/basket/items/'.length))));if(path==='/checkout'&&req.method==='POST'){const body=typeof req.body==='string'?JSON.parse(req.body):req.body;const method=body?.deliveryMethod;if(!['pickup','standard','express'].includes(method))return error(res,400,'INVALID_DELIVERY_METHOD','Select a valid delivery method before checkout.');return json(res,201,orderDto(await commerce.checkout(user,method)));}if(path==='/orders'&&req.method==='GET')return json(res,200,{orders:(await commerce.listOwnedOrders(user)).map(orderDto)});if(path.startsWith('/orders/')&&req.method==='GET')return json(res,200,orderDto(await commerce.getOwnedOrder(user,path.slice('/orders/'.length))));if(path==='/buckpay'&&req.method==='GET'){const a=await buckPay.getAccount(user);return json(res,200,{balance:a.balance,status:a.status});}if(path==='/buckpay/transactions'&&req.method==='GET'){const t=await buckPay.getTransactions(user);return json(res,200,{transactions:t.map(item=>({id:item.id,type:item.type,amount:item.amount,reference:item.reference,createdAt:item.createdAt}))});}return error(res,404,'NOT_FOUND','No such route.');}catch(err:any){const status=err?.code==='NOT_FOUND'?404:err?.code==='PRODUCT_UNAVAILABLE'?409:500;console.error('commerce-api error',err);return error(res,status,err?.code??'INTERNAL_ERROR',err instanceof Error?err.message:'Unexpected server error.');}}
