import { useMemo,useState } from 'react';
import { commerceClient,convertDisplayAmount,formatMoney,DELIVERY_OPTIONS,type Basket,type Product,type SupportedCurrency } from './api/commerce';

type Props={basket:Basket;products:Product[];currency:SupportedCurrency;onBasketChange:(basket:Basket)=>void;onContinue:()=>void;onBack:()=>void;};
export default function BasketPage({basket,products,currency,onBasketChange,onContinue,onBack}:Props){
 const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
 const byId=useMemo(()=>new Map(products.map(p=>[p.id,p])),[products]);
 const total=basket.items.reduce((sum,i)=>sum+convertDisplayAmount(i.unitPrice*i.quantity,i.currency,currency),0); const count=basket.items.reduce((sum,i)=>sum+i.quantity,0);
 async function change(productId:string,quantity:number){setBusy(productId);setError(null);try{const next=quantity<=0?await commerceClient.removeBasketItem(productId):await commerceClient.setBasketQuantity(productId,quantity);onBasketChange(next);}catch(e){setError(e instanceof Error?e.message:'Basket could not be updated.');}finally{setBusy(null);}}
 return <main className="cart-page"><div className="cart-page-header"><button className="quiet-button" type="button" onClick={onBack}>← Continue shopping</button><div><p className="eyebrow">YOUR BASKET</p><h1>{count} {count===1?'item':'items'}</h1><p className="hero-copy">This is your authoritative basket. Every change is saved to your account before the screen updates.</p></div></div>
 <div className="cart-page-grid"><section className="cart-page-card"><div className="cart-card-heading"><div><p className="eyebrow">BASKET ITEMS</p><h2>What you are buying</h2></div><span>{count} units</span></div>{basket.items.length===0?<div className="cart-empty"><h2>Your basket is empty</h2><p>Add products from the shop and they will appear here immediately.</p><button className="checkout-button" type="button" onClick={onBack}>Browse products</button></div>:<div className="cart-lines">{basket.items.map(item=>{const p=byId.get(item.productId);const line=convertDisplayAmount(item.unitPrice*item.quantity,item.currency,currency);const busy=busy===item.productId;return <article className="cart-line" key={item.productId}><div className="cart-line-image"><span>{(p?.name??'P').charAt(0)}</span></div><div className="cart-line-main"><strong>{p?.name??'Product'}</strong><span>{[p?.brand,p?.sizeLabel,p?.variantLabel].filter(Boolean).join(' · ')}</span><small>{formatMoney(convertDisplayAmount(item.unitPrice,item.currency,currency),currency)} each</small></div><div className="cart-line-actions"><div className="quantity-control"><button type="button" disabled={busy} onClick={()=>void change(item.productId,item.quantity-1)}>−</button><strong>{busy?'…':item.quantity}</strong><button type="button" disabled={busy} onClick={()=>void change(item.productId,item.quantity+1)}>+</button></div><strong>{formatMoney(line,currency)}</strong><button className="remove-button" type="button" disabled={busy} onClick={()=>void change(item.productId,0)}>Remove</button></div></article>})}</div>}</section>
 <aside className="cart-summary"><p className="eyebrow">ORDER SUMMARY</p><h2>Ready for checkout</h2><div className="cart-summary-row"><span>Items</span><strong>{formatMoney(total,currency)}</strong></div><div className="cart-summary-row"><span>Delivery</span><span>Selected at checkout</span></div><div className="cart-summary-total"><span>Basket total</span><strong>{formatMoney(total,currency)}</strong></div>{error&&<p className="checkout-error">{error}</p>}<button className="checkout-place-button" type="button" disabled={!basket.items.length||!!busy} onClick={onContinue}>Continue to checkout</button><p className="cart-trust">Your basket is server-authoritative. If a request fails, the displayed basket stays unchanged.</p></aside></div></main>;
}