import { useCallback,useEffect,useMemo,useState } from 'react';
import './styles.css';
type Store={id:string;code:string;name:string;status:string;region?:string};
type Event={id:string;event_type:string;entity_type:string;entity_id?:string;severity:'info'|'warning'|'critical';payload:Record<string,unknown>;created_at:string};
type Dashboard={store_id:string;generated_at:string;workload:{orders_paid:number;orders_fulfilling:number;orders_ready:number};exceptions:{unavailable_items:number;partial_items:number;failed_deliveries:number;low_stock_items:number};recent_events:Event[]};
type Fulfilment={id:string;order_id:string;store_id:string;status:string;created_at:string;updated_at:string;handed_off_at?:string};
type FulfilmentItem={id:string;fulfilment_id:string;order_item_id:string;requested_quantity:number;picked_quantity:number;status:string;substitution_product_id?:string|null;substitution_quantity?:number|null;notes?:string|null;order_items?:{product_id:string;products?:{id:string;name:string}|null}|null};
const token=()=>{try{for(const key of Object.keys(localStorage)){if(!key.startsWith('sb-')||!key.endsWith('-auth-token'))continue;const p=JSON.parse(localStorage.getItem(key)||'{}');const s=p.currentSession||p;if(s?.access_token)return s.access_token;}}catch{}return '';};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const t=token();if(!t)throw new Error('Sign in with an authorized store account to continue.');const r=await fetch(path,{...init,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...(init?.headers||{})}});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.error?.message||body?.message||'Request failed ('+r.status+')');return body as T;}
const label=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function OpsDashboard(){
 const[stores,setStores]=useState<Store[]>([]),[storeId,setStoreId]=useState(''),[data,setData]=useState<Dashboard|null>(null),[fulfilments,setFulfilments]=useState<Fulfilment[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[live,setLive]=useState(false),[selected,setSelected]=useState<Fulfilment|null>(null),[items,setItems]=useState<FulfilmentItem[]>([]),[itemBusy,setItemBusy]=useState<string|null>(null);
 const store=useMemo(()=>stores.find(s=>s.id===storeId),[stores,storeId]);
 const load=useCallback(async(id:string)=>{if(!id)return;setLoading(true);setError(null);try{const[d,f]=await Promise.all([api<Dashboard>('/api/ops/dashboard/'+id),api<{fulfilments:Fulfilment[]}>('/api/ops/fulfilments')]);setData(d);setFulfilments(f.fulfilments.filter(x=>x.store_id===id));}catch(e){setError(e instanceof Error?e.message:'Operations data could not be loaded.');}finally{setLoading(false);}},[]);
 useEffect(()=>{api<{stores:Store[]}>('/api/ops/stores').then(x=>{setStores(x.stores);if(x.stores[0])setStoreId(x.stores[0].id);}).catch(e=>setError(e instanceof Error?e.message:'Store access could not be loaded.')).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(storeId)void load(storeId);},[storeId,load]);
 useEffect(()=>{if(!storeId||!live)return;const timer=window.setInterval(()=>void load(storeId),10000);return()=>window.clearInterval(timer);},[storeId,load,live]);
 const act=async(kind:string,id:string)=>{setBusy(id);setError(null);try{await api(kind==='start'?'/api/ops/orders/'+id+'/fulfil':'/api/ops/orders/'+id+'/complete',{method:'POST',body:JSON.stringify({handOff:kind==='handoff'})});await load(storeId);}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}finally{setBusy(null);}};
 const openFulfilment=async(f:Fulfilment)=>{setSelected(f);setError(null);try{const r=await api<{items:FulfilmentItem[]}>('/api/ops/fulfilments/'+f.id+'/items');setItems(r.items);}catch(e){setError(e instanceof Error?e.message:'Fulfilment items could not be loaded.');}};
 const saveItem=async(item:FulfilmentItem,pickedQuantity:number)=>{setItemBusy(item.id);setError(null);try{await api('/api/ops/fulfilments/'+item.id,{method:'POST',body:JSON.stringify({pickedQuantity})});const r=await api<{items:FulfilmentItem[]}>('/api/ops/fulfilments/'+item.fulfilment_id+'/items');setItems(r.items);await load(storeId);}catch(e){setError(e instanceof Error?e.message:'Picking update failed.');}finally{setItemBusy(null);}};

 const actionable=fulfilments.filter(f=>['ready','partial','started','in_progress','picking'].includes(f.status)||data?.recent_events.some(e=>e.entity_id===f.id&&e.severity!=='info'));
 return <div className='ops-shell'><header className='ops-topbar'><div className='brand-mark'><span className='brand-e'>e</span><span>Essentials Mart · Store Operations</span></div><div className='ops-actions'><span className={live?'ops-live active':'ops-live'}><i/>Live</span><select value={storeId} onChange={e=>setStoreId(e.target.value)} disabled={!stores.length}>{stores.map(s=><option key={s.id} value={s.id}>{s.name} · {s.code}</option>)}</select><button type='button' onClick={()=>void load(storeId)} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div></header>
 <main className='ops-main'><div className='ops-heading'><div><p className='eyebrow'>CONTROL SURFACE</p><h1>{store?.name||'Store operations'}</h1><p>Live workload, fulfilment exceptions and inventory signals for authorized store staff.</p></div><div className='ops-updated'>{data?'Updated '+new Date(data.generated_at).toLocaleTimeString():'Waiting for store data'}</div></div>
 {error&&<div className='ops-error'>{error}</div>}{loading&&!data?<div className='ops-state'>Loading operational intelligence…</div>:data&&<><section className='ops-metrics'><article><span>Paid orders</span><strong>{data.workload.orders_paid}</strong><small>Awaiting fulfilment</small></article><article><span>Fulfilling</span><strong>{data.workload.orders_fulfilling}</strong><small>Active picking workload</small></article><article><span>Ready</span><strong>{data.workload.orders_ready}</strong><small>Ready for hand-off</small></article><article className='warning'><span>Exceptions</span><strong>{data.exceptions.unavailable_items+data.exceptions.partial_items}</strong><small>{data.exceptions.unavailable_items} unavailable · {data.exceptions.partial_items} partial</small></article><article className='critical'><span>Delivery failures</span><strong>{data.exceptions.failed_deliveries}</strong><small>Requires intervention</small></article><article className='warning'><span>Low stock</span><strong>{data.exceptions.low_stock_items}</strong><small>At or below threshold</small></article></section>
 <section className='ops-grid'><div className='ops-panel'><div className='ops-panel-head'><div><p className='eyebrow'>FULFILMENT QUEUE</p><h2>Orders requiring action</h2></div></div><div className='exception-list'>{actionable.slice(0,12).map(f=><div className='exception-row' key={f.id}><span className='severity'>{label(f.status)}</span><div><strong>Order {f.order_id.slice(0,8)}</strong><small>Fulfilment {f.id.slice(0,8)}</small></div><div className='ops-row-actions'><button type='button' onClick={()=>void openFulfilment(f)}>Pick items</button><button type='button' disabled={busy===f.order_id} onClick={()=>void act(f.status==='ready'?'start':'handoff',f.order_id)}>{busy===f.order_id?'Working…':f.status==='ready'?'Start fulfilment':'Complete handoff'}</button></div></div>)}{actionable.length===0&&<div className='ops-empty'>No fulfilments currently require action.</div>}</div></div>
 <div className='ops-panel'><div className='ops-panel-head'><div><p className='eyebrow'>EXCEPTION QUEUE</p><h2>Needs attention</h2></div><button type='button' onClick={()=>setLive(v=>!v)}>{live?'Pause live':'Enable live'}</button></div><div className='event-list'>{data.recent_events.filter(e=>e.severity!=='info').slice(0,12).map(e=><div className='event-row' key={e.id}><span className={'event-dot '+e.severity}/><div><strong>{label(e.event_type)}</strong><small>{label(e.entity_type)} {e.entity_id?'· '+e.entity_id.slice(0,8):''}</small></div><time>{new Date(e.created_at).toLocaleString()}</time></div>)}{data.recent_events.filter(e=>e.severity!=='info').length===0&&<div className='ops-empty'>No warning or critical events in the latest event window.</div>}</div></div></section></>}</main></div>;
}