import { randomUUID } from "node:crypto";
import { CommerceError, placeOrder } from "../commerce.js";
import type { AuthenticatedPrincipal, Basket, Product, Order, DeliveryMethod } from "../domain.js";
import type { ProductRepository } from "../ports/ProductRepository.js";
import type { BasketRepository } from "../ports/BasketRepository.js";
import type { OrderRepository } from "../ports/OrderRepository.js";
import type { CheckoutTransaction } from "../ports/CheckoutTransaction.js";
export class CommerceApplicationService {
  constructor(private readonly products:ProductRepository,private readonly baskets:BasketRepository,private readonly orders:OrderRepository,private readonly transaction:CheckoutTransaction){}
  async listProducts(){return this.products.list();}
  async getProduct(id:string){const p=await this.products.getById(id);if(!p)throw new CommerceError(`Product not found: ${id}`,"NOT_FOUND");return p;}
  async getOrCreateBasket(principal:AuthenticatedPrincipal){const existing=await this.baskets.getByCustomerId(principal.customerId);if(existing)return existing;const basket:Basket={id:randomUUID(),customerId:principal.customerId,lines:[]};await this.baskets.save(basket);return basket;}
  async addItem(principal:AuthenticatedPrincipal,productId:string,quantity:number){if(!Number.isInteger(quantity)||quantity<=0)throw new CommerceError("Quantity must be a positive integer","INVALID_QUANTITY");const product=await this.products.getById(productId);if(!product)throw new CommerceError(`Product not found: ${productId}`,"NOT_FOUND");if(!product.available)throw new CommerceError(`Product unavailable: ${productId}`,"PRODUCT_UNAVAILABLE");const basket=await this.getOrCreateBasket(principal);const lines=structuredClone(basket.lines);const existing=lines.find(l=>l.productId===product.id);if(existing)existing.quantity+=quantity;else lines.push({productId:product.id,quantity,unitPrice:structuredClone(product.price)});const updated={...basket,lines};await this.baskets.save(updated);return updated;}
  async removeItem(principal:AuthenticatedPrincipal,productId:string){const basket=await this.getOrCreateBasket(principal);const lines=basket.lines.filter(l=>l.productId!==productId);if(lines.length===basket.lines.length)throw new CommerceError(`Basket has no line for product: ${productId}`,"LINE_NOT_FOUND");const updated={...basket,lines};await this.baskets.save(updated);return updated;}
  async checkout(principal:AuthenticatedPrincipal,deliveryMethod:DeliveryMethod){const basket=await this.getOrCreateBasket(principal);if(!basket.lines.length)throw new CommerceError("Basket must contain at least one item","BASKET_EMPTY");const products=await Promise.all(basket.lines.map(async line=>({line,product:await this.products.getById(line.productId)})));const freshProducts=new Map<string,Product>();for(const {line,product} of products){if(product)freshProducts.set(line.productId,product);}const order=placeOrder(principal,basket,freshProducts,randomUUID(),deliveryMethod);if(this.transaction.commitCheckout)return await this.transaction.commitCheckout({customerId:principal.customerId,basketId:basket.id,order}) as Order;return this.transaction.run(async()=>{await this.orders.save(order);await this.baskets.save({...basket,lines:[]});return order;});}
  async getOwnedOrder(principal:AuthenticatedPrincipal,orderId:string){const order=await this.orders.getOwnedById(principal.customerId,orderId);if(!order)throw new CommerceError(`Order not found: ${orderId}`,"NOT_FOUND");return order;}
  async listOwnedOrders(principal:AuthenticatedPrincipal){return this.orders.listOwnedByCustomer(principal.customerId);}
}
