alter table public.walk_layouts enable row level security;
alter table public.walk_aisles enable row level security;
alter table public.walk_product_positions enable row level security;
alter table public.walk_navigation_nodes enable row level security;
alter table public.walk_navigation_edges enable row level security;
alter table public.walk_sessions enable row level security;
create policy walk_layouts_authenticated_select on public.walk_layouts for select to authenticated using(status='active');
create policy walk_aisles_authenticated_select on public.walk_aisles for select to authenticated using(exists(select 1 from public.walk_layouts l where l.id=layout_id and l.status='active'));
create policy walk_product_positions_authenticated_select on public.walk_product_positions for select to authenticated using(status='active' and exists(select 1 from public.walk_layouts l where l.id=layout_id and l.status='active'));
create policy walk_navigation_nodes_authenticated_select on public.walk_navigation_nodes for select to authenticated using(exists(select 1 from public.walk_layouts l where l.id=layout_id and l.status='active'));
create policy walk_navigation_edges_authenticated_select on public.walk_navigation_edges for select to authenticated using(status='OPEN' and exists(select 1 from public.walk_layouts l where l.id=layout_id and l.status='active'));
create policy walk_sessions_owner_select on public.walk_sessions for select to authenticated using((select auth.uid())=(select c.auth_user_id from public.customers c where c.id=customer_id));
create policy walk_sessions_owner_insert on public.walk_sessions for insert to authenticated with check((select auth.uid())=(select c.auth_user_id from public.customers c where c.id=customer_id));
create policy walk_sessions_owner_update on public.walk_sessions for update to authenticated using((select auth.uid())=(select c.auth_user_id from public.customers c where c.id=customer_id)) with check((select auth.uid())=(select c.auth_user_id from public.customers c where c.id=customer_id));
create index if not exists walk_aisles_layout_idx on public.walk_aisles(layout_id);
create index if not exists walk_product_positions_product_idx on public.walk_product_positions(product_id,layout_id);
create index if not exists walk_product_positions_aisle_idx on public.walk_product_positions(aisle_id);
create index if not exists walk_navigation_nodes_layout_idx on public.walk_navigation_nodes(layout_id);
create index if not exists walk_navigation_edges_from_idx on public.walk_navigation_edges(from_node_id,status);
create index if not exists walk_navigation_edges_to_idx on public.walk_navigation_edges(to_node_id);
create index if not exists walk_sessions_customer_idx on public.walk_sessions(customer_id,created_at desc);
create index if not exists walk_sessions_store_idx on public.walk_sessions(store_id);
create index if not exists walk_sessions_layout_idx on public.walk_sessions(layout_id);
create index if not exists walk_sessions_current_node_idx on public.walk_sessions(current_node_id);
