function json(res:any,status:number,body:unknown){return res.status(status).setHeader('Content-Type','application/json').setHeader('Cache-Control','no-store').json(body);}
function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Basket database configuration is missing.');return{url:url.replace(/\/$/,''),key};}
async function db<T>(path:string,init:RequestInit={}):Promise<T>{const{url,key}=config();const r=await fetch(url+'/rest/v1/'+path,{...init,headers:{apikey:key,Authorization:'Bearer '+key,Accept:'application/json','Content-Type':'application/json',...(init.headers??{})}});const text=await r.text();if(!r.ok)throw new Error('Basket database request failed ('+r.status+'): '+text.slice(0,300));return(text?JSON.parse(text):null) as T;}
async function principal(req:any){const auth=String(req.headers?.authorization??req.headers?.Authorization??'');if(!auth.startsWith('Bearer '))return null;const {url,key}=config();const r=await fetch(url+'/auth/v1/user',{headers:{apikey:key,Authorization:auth}});if(!r.ok)return null;const user=await r.json();if(!user?.id)return null;const customers=await db<Array<{id:string;external_customer_id:string|null}>>('customers?select=id,external_customer_id&auth_user_id=eq.'+encodeURIComponent(user.id)+'&limit=1');const customer=customers[0];if(!customer)return null;return{customerId:customer.external_customer_id??customer.id,authUserId:user.id};}
async function resolveBasket(externalCustomerId:string){const customers=await db<Array<{id:string}>>('customers?select=id&external_customer_id=eq.'+encodeURIComponent(externalCustomerId)+'&limit=1');if(!customers[0])throw new Error('Authenticated user has no customer identity.');const baskets=await db<any[]>('baskets?select=id,currency,status&customer_id=eq.'+encodeURIComponent(customers[0].id)+'&status=eq.active&order=updated_at.desc&limit=1');if(baskets[0])return baskets[0];const created=await db<any[]>('baskets',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({customer_id:customers[0].id,status:'active',currency:'USD',updated_at:new Date().toISOString()})});if(!created[0])throw new Error('Could not create the active basket.');return created[0];}
async function stockFor(productId:string){const stores=await db<any[]>('stores?select=id&code=eq.MAIN&limit=1');if(!stores[0])return 0;const rows=await db<any[]>('inventory?select=quantity,reserved_quantity&store_id=eq.'+encodeURIComponent(stores[0].id)+'&product_id=eq.'+encodeURIComponent(productId)+'&limit=1');return Math.max(0,Number(rows[0]?.quantity??0)-Number(rows[0]?.reserved_quantity??0));}
async function readBasket(basket:any){const rows=await db<any[]>('basket_items?select=id,product_id,quantity,unit_price,products(id,name,brand,category,size_label,variant_label,image_url,is_active,currency)&basket_id=eq.'+encodeURIComponent(basket.id)+'&order=created_at.asc');const lines=[];for(const x of rows){lines.push({id:x.id,productId:x.product_id,quantity:Number(x.quantity),unitPrice:{amountMinor:Math.round(Number(x.unit_price)*100),currency:basket.currency},product:{id:x.products?.id??x.product_id,name:x.products?.name??'Product',brand:x.products?.brand??undefined,category:x.products?.category??undefined,sizeLabel:x.products?.size_label??undefined,variantLabel:x.products?.variant_label??undefined,imageUrl:x.products?.image_url??undefined,available:Boolean(x.products?.is_active),stockQuantity:await stockFor(x.product_id)}});}return{id:basket.id,currency:basket.currency,lines};}
export default async function handler(req:any,res:any){if(!['GET','POST','PATCH','DELETE'].includes(req.method))return json(res,405,{error:{code:'METHOD_NOT_ALLOWED',message:'Basket supports GET, POST, PATCH and DELETE.'}});try{const user=await principal(req);if(!user)return json(res,401,{error:{code:'UNAUTHENTICATED',message:'A valid Supabase Auth session is required.'}});const basket=await resolveBasket(user.customerId);
 if(req.method==='GET')return json(res,200,await readBasket(basket));
 const body=typeof req.body==='string'?JSON.parse(req.body):(req.body??{});const productId=String(body.productId??'').trim();if(!productId)return json(res,400,{error:{code:'VALIDATION_ERROR',message:'productId is required.'}});
 const products=await db<any[]>('products?select=id,name,brand,category,size_label,variant_label,image_url,price,currency,is_active&id=eq.'+encodeURIComponent(productId)+'&limit=1');const product=products[0];if(!product||!product.is_active)return json(res,409,{error:{code:'PRODUCT_UNAVAILABLE',message:'That product is no longer available.'}});if(product.currency!==basket.currency)return json(res,409,{error:{code:'CURRENCY_MISMATCH',message:'Basket currency is '+basket.currency+' and this product is '+product.currency+'.'}});
 const available=await stockFor(productId);const existing=await db<any[]>('basket_items?select=id,quantity&basket_id=eq.'+encodeURIComponent(basket.id)+'&product_id=eq.'+encodeURIComponent(productId)+'&limit=1');const current=Number(existing[0]?.quantity??0);
 if(req.method==='DELETE'){if(existing[0])await db('basket_items?id=eq.'+encodeURIComponent(existing[0].id),{method:'DELETE',headers:{Prefer:'return=minimal'}});}
 if(req.method==='POST'){const add=Math.max(1,Math.min(100,Math.floor(Number(body.quantity)||1)));const next=current+add;if(next>available)return json(res,409,{error:{code:'INSUFFICIENT_STOCK',message:'Only '+available+' units are available.'}});if(existing[0])await db('basket_items?id=eq.'+encodeURIComponent(existing[0].id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({quantity:next,unit_price:Number(product.price)})});else await db('basket_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({basket_id:basket.id,product_id:productId,quantity:add,unit_price:Number(product.price)})});}
 if(req.method==='PATCH'){const quantity=Number(body.quantity);if(!Number.isInteger(quantity)||quantity<0||quantity>100)return json(res,400,{error:{code:'VALIDATION_ERROR',message:'quantity must be an integer between 0 and 100.'}});if(quantity>available)return json(res,409,{error:{code:'INSUFFICIENT_STOCK',message:'Only '+available+' units are available.'}});if(quantity===0){if(existing[0])await db('basket_items?id=eq.'+encodeURIComponent(existing[0].id),{method:'DELETE',headers:{Prefer:'return=minimal'}});}else if(existing[0])await db('basket_items?id=eq.'+encodeURIComponent(existing[0].id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({quantity,unit_price:Number(product.price)})});else await db('basket_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({basket_id:basket.id,product_id:productId,quantity,unit_price:Number(product.price)})});}
 await db('baskets?id=eq.'+encodeURIComponent(basket.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({updated_at:new Date().toISOString()})});return json(res,200,await readBasket(basket));
 }catch(e){console.error('basket-api error',e);return json(res,500,{error:{code:'BASKET_FAILED',message:e instanceof Error?e.message:'Basket operation failed.'}});}}