function json(res:any,status:number,body:unknown){return res.status(status).setHeader('Content-Type','application/json').setHeader('Cache-Control','no-store').json(body);}
function money(amount:number,currency:string){return{amountMinor:Math.round(Number(amount)*100),currency};}
import crypto from 'node:crypto';
export default async function handler(req:any,res:any){
 if(req.method!=='POST')return json(res,405,{error:{code:'METHOD_NOT_ALLOWED',message:'Checkout requires POST.'}});
 try{
  const {principal}=await import('../apps/customer_web/api/_auth.js'); const user=await principal(req);
  if(!user)return json(res,401,{error:{code:'UNAUTHENTICATED',message:'A valid Supabase Auth session is required.'}});
  const body=typeof req.body==='string'?JSON.parse(req.body):(req.body??{}); const method=body?.deliveryMethod; const idempotencyKey=String(req.headers?.['idempotency-key']??req.headers?.['Idempotency-Key']??'').trim();
  if(!['pickup','standard','express'].includes(method))return json(res,400,{error:{code:'INVALID_DELIVERY_METHOD',message:'Select pickup, standard, or express.'}});
  if(!idempotencyKey||idempotencyKey.length>200)return json(res,400,{error:{code:'INVALID_IDEMPOTENCY_KEY',message:'A valid Idempotency-Key is required.'}});
  const {url,key}=(()=>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Checkout database configuration is missing.');return{url:url.replace(/\\/$/,''),key};})();
  const db=async(path:string,init:RequestInit={})=>{const r=await fetch(url+'/rest/v1/'+path,{...init,headers:{apikey:key,Authorization:'Bearer '+key,Accept:'application/json','Content-Type':'application/json',...(init.headers??{})}});const text=await r.text();if(!r.ok)throw new Error('Checkout database request failed ('+r.status+'): '+text.slice(0,300));return text?JSON.parse(text):null;};
  const customers=await db('customers?select=id&external_customer_id=eq.'+encodeURIComponent(user.customerId)+'&limit=1'); if(!customers[0])return json(res,409,{error:{code:'CUSTOMER_NOT_FOUND',message:'Authenticated customer identity was not found.'}});
  const customerId=customers[0].id; const fingerprint='deliveryMethod:'+method;
  const existingKeys=await db('checkout_idempotency_keys?select=idempotency_key,request_fingerprint,order_id&customer_id=eq.'+encodeURIComponent(customerId)+'&idempotency_key=eq.'+encodeURIComponent(idempotencyKey)+'&limit=1');
  if(existingKeys[0]){const existing=existingKeys[0];if(existing.request_fingerprint!==fingerprint)return json(res,409,{error:{code:'IDEMPOTENCY_KEY_REUSED',message:'This Idempotency-Key was already used for a different checkout request.'}});if(existing.order_id){const existingOrders=await db('orders?select=id,status,subtotal,total,currency,delivery_method,delivery_fee,created_at&customer_id=eq.'+encodeURIComponent(customerId)+'&id=eq.'+encodeURIComponent(existing.order_id)+'&limit=1');const existingOrder=existingOrders[0];if(existingOrder){const existingLines=await db('order_items?select=product_id,quantity,unit_price&order_id=eq.'+encodeURIComponent(existingOrder.id)+'&order=created_at.asc');return json(res,200,{id:existingOrder.id,status:existingOrder.status,subtotal:money(existingOrder.subtotal,existingOrder.currency),deliveryMethod:existingOrder.delivery_method,deliveryFee:money(existingOrder.delivery_fee,existingOrder.currency),total:money(existingOrder.total,existingOrder.currency),currency:existingOrder.currency,lines:existingLines.map((x:any)=>({productId:x.product_id,quantity:Number(x.quantity),unitPrice:money(x.unit_price,existingOrder.currency)})),createdAt:existingOrder.created_at});}}}
  const baskets=await db('baskets?select=id,currency,status&customer_id=eq.'+encodeURIComponent(customerId)+'&status=eq.active&order=updated_at.desc&limit=1'); const basket=baskets[0]; if(!basket)return json(res,400,{error:{code:'BASKET_EMPTY',message:'Your basket is empty.'}});
  const orderId=crypto.randomUUID();
  const rpc=await db('rpc/checkout_basket',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({p_customer_external_id:user.customerId,p_order_id:orderId,p_basket_id:basket.id,p_delivery_method:method,p_idempotency_key:idempotencyKey,p_request_fingerprint:fingerprint})});
  const result=Array.isArray(rpc)?rpc[0]:rpc;
  if(!result)throw new Error('Checkout transaction returned no order.');
  return json(res,result.idempotent?200:201,{id:result.id,status:result.status,subtotal:result.subtotal,deliveryMethod:result.deliveryMethod,deliveryFee:result.deliveryFee,total:result.total,currency:result.total?.currency??basket.currency,lines:(result.lines??[]).map((x:any)=>({productId:x.productId,quantity:Number(x.quantity),unitPrice:money(x.unitPrice,result.total?.currency??basket.currency)})),createdAt:result.createdAt??null,idempotent:result.idempotent??false});
 }catch(error:any){console.error('checkout-api error',error);return json(res,500,{error:{code:error?.code??'CHECKOUT_FAILED',message:error instanceof Error?error.message:'Checkout failed.'}});}
}