async function principal(req:any){ const auth=await import('../apps/customer_web/api/_auth.js'); return auth.principal(req); }

type Row=Record<string,any>;
const json=(res:any,status:number,body:unknown)=>res.status(status).setHeader('Content-Type','application/json').setHeader('Cache-Control','no-store').json(body);
function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase household configuration is missing.');return{url:url.replace(/\/$/,''),key};}
async function supabase<T>(path:string,init?:RequestInit):Promise<T>{const{url,key}=config();const r=await fetch(url+'/rest/v1/'+path,{...init,headers:{apikey:key,Authorization:'Bearer '+key,Accept:'application/json','Content-Type':'application/json',...(init?.headers??{})}});if(!r.ok)throw new Error('Supabase pantry request failed ('+r.status+'): '+(await r.text()).slice(0,300));if(r.status===204)return undefined as T;return await r.json() as T;}
export default async function handler(req:any,res:any){
 if(!['GET','POST','PATCH','DELETE'].includes(req.method))return res.status(405).json({error:{message:'Method not allowed.'}});
 try{
  const user=await principal(req);if(!user)return json(res,401,{error:{code:'UNAUTHENTICATED',message:'A valid Supabase Auth session is required.'}});
  const customers=await supabase<Array<{id:string}>>('customers?auth_user_id=eq.'+encodeURIComponent(user.authUserId)+'&select=id&limit=1');const customer=customers[0]?.id;if(!customer)return json(res,404,{error:{code:'CUSTOMER_NOT_FOUND',message:'Authenticated user has no customer identity.'}});
  const memberships=await supabase<Array<{household_id:string}>>('household_memberships?customer_id=eq.'+encodeURIComponent(customer)+'&status=eq.active&select=household_id&limit=1');const householdId=memberships[0]?.household_id;if(!householdId)return json(res,404,{error:{code:'HOUSEHOLD_NOT_FOUND',message:'No active household exists.'}});
  const body=typeof req.body==='string'?JSON.parse(req.body):(req.body??{}), id=String(req.query?.id??body.id??'').trim();
  if(req.method==='GET'){const items=await supabase<Row[]>('household_pantry_items?household_id=eq.'+encodeURIComponent(householdId)+'&select=id,household_id,product_id,product_name,quantity,unit,status,source,last_confirmed_at,created_at,updated_at&order=product_name.asc');return json(res,200,{pantry:items});}
  if(req.method==='POST'){const name=String(body.productName??'').trim();const quantity=Math.max(0,Number(body.quantity??1));if(!name)return json(res,400,{error:{code:'PANTRY_NAME_REQUIRED',message:'Product name is required.'}});const status=['available','low','depleted'].includes(body.status)?body.status:(quantity<=0?'depleted':quantity<=1?'low':'available');const rows=await supabase<Row[]>('household_pantry_items',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({household_id:householdId,product_id:body.productId||null,product_name:name,quantity,unit:String(body.unit??'unit'),status,source:'manual',last_confirmed_at:new Date().toISOString()})});return json(res,201,{item:rows[0]});}
  if(!id)return json(res,400,{error:{code:'PANTRY_ID_REQUIRED',message:'Pantry item id is required.'}});
  const existing=await supabase<Row[]>('household_pantry_items?id=eq.'+encodeURIComponent(id)+'&household_id=eq.'+encodeURIComponent(householdId)+'&select=id&limit=1');if(!existing[0])return json(res,404,{error:{code:'PANTRY_ITEM_NOT_FOUND',message:'Pantry item not found.'}});
  if(req.method==='DELETE'){await supabase('household_pantry_items?id=eq.'+encodeURIComponent(id)+'&household_id=eq.'+encodeURIComponent(householdId),{method:'DELETE'});return json(res,200,{deleted:true});}
  const quantity=body.quantity===undefined?undefined:Math.max(0,Number(body.quantity));const status=body.status!==undefined?body.status:(quantity===undefined?undefined:quantity<=0?'depleted':quantity<=1?'low':'available');const updates:any={updated_at:new Date().toISOString(),last_confirmed_at:new Date().toISOString()};if(quantity!==undefined)updates.quantity=quantity;if(['available','low','depleted'].includes(status))updates.status=status;if(body.unit!==undefined)updates.unit=String(body.unit).trim()||'unit';const rows=await supabase<Row[]>('household_pantry_items?id=eq.'+encodeURIComponent(id)+'&household_id=eq.'+encodeURIComponent(householdId),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(updates)});return json(res,200,{item:rows[0]??null});
 }catch(e){console.error('household-pantry-api error',e);return json(res,500,{error:{code:'HOUSEHOLD_PANTRY_INTERNAL_ERROR',message:e instanceof Error?e.message:'Pantry service unavailable.'}});}
}